# Force OS X.
language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

# Remove Xcode and CommandLineTools included in default OS X image.
# This ensures the Command Line Tool install functionality is tested.
before_script:
  - sudo rm -rf /Applications/Xcode.app /Library/Developer/CommandLineTools
  - sudo pkgutil --forget com.apple.pkg.CLTools_Executables

script:
  - ./uninstall -d
  - ./uninstall -f
  - ./install
  - brew install ack

notifications:
  email: false
