name: reviewdog
on: [pull_request]
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Test shell scripts with shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
