name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    strategy:
      matrix:
        os:
        - macOS-latest
        - ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Set up Ruby
      if: runner.os == 'Linux'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install RubyGems
      run: |
        gem install bundler -v "~>1"
        bundle install --retry=3 --jobs=4

    - name: Run RuboCop
      run: |
        bundle exec rubocop

    - name: Cleanup macOS
      if: runner.os == 'macOS'
      run: |
        sudo rm -rf /Applications/Xcode.app \
                    /Library/Developer/CommandLineTools
        sudo xcode-select --reset

    - name: Set up Homebrew PATH
      run: |
        if [ "$RUNNER_OS" = "macOS" ]; then
          echo "::add-path::/usr/local/bin:/usr/bin:/bin"
        else
          echo "::add-path::/home/linuxbrew/.linuxbrew/bin:/usr/bin:/bin"
        fi

    - name: Test uninstalling GitHub Actions macOS Homebrew
      if: runner.os == 'macOS'
      run: |
        bash uninstall.sh -d >/dev/null
        bash uninstall.sh -f >/dev/null

    - name: Test install.sh
      run: |
        bash install.sh
        brew install ack
        bash uninstall.sh -f >/dev/null
        bash install.sh

    - name: Install Shellcheck
      run: brew install shellcheck

    - name: Run Shellcheck
      run: shellcheck *.sh

    - name: Test uninstalling newly installed Homebrew
      run: |
        bash uninstall.sh -d >/dev/null
        bash uninstall.sh -f >/dev/null
